# Generated by Django 6.0.6 on 2026-07-13 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HistoryTime', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('HistoryProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.product', verbose_name='浏览商品')),
                ('HistoryUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览历史',
                'verbose_name_plural': '浏览历史',
                'ordering': ['-HistoryTime'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileAvatar', models.ImageField(blank=True, default='', upload_to='avatars/', verbose_name='头像')),
                ('ProfilePhone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('ProfileAddress', models.CharField(blank=True, default='', max_length=300, verbose_name='默认地址')),
                ('ProfileGender', models.CharField(choices=[('Male', '男'), ('Female', '女'), ('Other', '其他')], default='Other', max_length=10, verbose_name='性别')),
                ('ProfileBirthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('ProfileUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
