# Generated by Django 6.0.6 on 2026-07-13 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageSession', models.CharField(default='', max_length=100, verbose_name='会话ID')),
                ('MessageRole', models.CharField(choices=[('user', '用户'), ('bot', '机器人')], default='user', max_length=20, verbose_name='消息角色')),
                ('MessageContent', models.TextField(verbose_name='消息内容')),
                ('MessageMode', models.CharField(choices=[('keyword', '关键词匹配'), ('llm', '大模型'), ('default', '默认回复')], default='default', max_length=20, verbose_name='回复模式')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('MessageUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天记录',
                'verbose_name_plural': '聊天记录',
                'ordering': ['CreateTime'],
            },
        ),
        migrations.CreateModel(
            name='KeywordRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RuleKeyword', models.CharField(max_length=100, verbose_name='关键词')),
                ('RuleResponse', models.TextField(verbose_name='回复内容')),
                ('RulePriority', models.IntegerField(default=0, verbose_name='优先级')),
                ('IsEnabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('RuleCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Goods.category', verbose_name='关联分类')),
            ],
            options={
                'verbose_name': '关键词规则',
                'verbose_name_plural': '关键词规则',
                'ordering': ['-RulePriority'],
            },
        ),
    ]
