# Generated by Django 6.0.6 on 2026-07-13 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('CategoryIcon', models.CharField(blank=True, default='fas fa-laptop', max_length=100, verbose_name='分类图标')),
                ('CategoryDesc', models.TextField(blank=True, default='', verbose_name='分类描述')),
                ('CategorySort', models.IntegerField(default=0, verbose_name='排序权重')),
                ('IsVisible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['CategorySort', '-CreateTime'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200, verbose_name='商品名称')),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('ProductOriginalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='原价')),
                ('ProductImage', models.ImageField(blank=True, default='', upload_to='products/', verbose_name='商品图片')),
                ('ProductDesc', models.TextField(blank=True, default='', verbose_name='商品描述')),
                ('ProductDetail', models.TextField(blank=True, default='', verbose_name='商品详情')),
                ('ProductSpecs', models.JSONField(blank=True, default=dict, verbose_name='商品规格')),
                ('ProductStock', models.IntegerField(default=100, verbose_name='库存数量')),
                ('ProductSales', models.IntegerField(default=0, verbose_name='销量')),
                ('ProductTags', models.CharField(blank=True, default='', max_length=200, verbose_name='商品标签')),
                ('IsNew', models.BooleanField(default=True, verbose_name='是否新品')),
                ('IsHot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('IsRecommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('IsOnSale', models.BooleanField(default=False, verbose_name='是否促销')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Goods.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-CreateTime'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewRating', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], default=5, verbose_name='评分')),
                ('ReviewContent', models.TextField(max_length=500, verbose_name='评价内容')),
                ('ReviewTime', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('ReviewProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Goods.product', verbose_name='评价商品')),
                ('ReviewUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评价用户')),
            ],
            options={
                'verbose_name': '商品评价',
                'verbose_name_plural': '商品评价',
                'ordering': ['-ReviewTime'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FavoriteTime', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('FavoriteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
                ('FavoriteProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='Goods.product', verbose_name='收藏商品')),
            ],
            options={
                'verbose_name': '商品收藏',
                'verbose_name_plural': '商品收藏',
                'unique_together': {('FavoriteUser', 'FavoriteProduct')},
            },
        ),
    ]
