# Generated by Django 6.0.6 on 2026-07-13 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CartQuantity', models.IntegerField(default=1, verbose_name='商品数量')),
                ('CartIsSelected', models.BooleanField(default=True, verbose_name='是否选中')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('CartProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.product', verbose_name='商品')),
                ('CartUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车项',
                'verbose_name_plural': '购物车项',
                'unique_together': {('CartUser', 'CartProduct')},
            },
        ),
    ]
