# Generated by Django 6.0.6 on 2026-07-13 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNo', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='订单编号')),
                ('OrderTotalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总价')),
                ('OrderStatus', models.CharField(choices=[('Pending', '待支付'), ('Paid', '已支付'), ('Shipped', '已发货'), ('Completed', '已完成'), ('Cancelled', '已取消')], default='Pending', max_length=20, verbose_name='订单状态')),
                ('OrderPayMethod', models.CharField(choices=[('Alipay', '支付宝'), ('WeChat', '微信支付'), ('BankCard', '银行卡')], default='Alipay', max_length=20, verbose_name='支付方式')),
                ('OrderAddress', models.CharField(default='', max_length=300, verbose_name='收货地址')),
                ('OrderPhone', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('OrderReceiver', models.CharField(default='', max_length=50, verbose_name='收货人')),
                ('OrderRemark', models.TextField(blank=True, default='', verbose_name='订单备注')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('OrderUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-CreateTime'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemProductName', models.CharField(default='', max_length=200, verbose_name='商品名称')),
                ('ItemProductImage', models.CharField(default='', max_length=300, verbose_name='商品图片')),
                ('ItemPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品单价')),
                ('ItemQuantity', models.IntegerField(default=1, verbose_name='商品数量')),
                ('ItemTotalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='小计金额')),
                ('ItemOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Order.order', verbose_name='所属订单')),
                ('ItemProduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Goods.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
            },
        ),
    ]
